name: hybrid_states_sample
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  json_annotation: ^4.0.1

  # Redux
  redux: ^5.0.0
  flutter_redux: ^0.8.2

  # Provider
  provider: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  flutter_lints: ^1.0.4
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
